# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master", "v1", "release" ]
    tags: ['*']
  pull_request:
    branches: [ "master", "v1", "release" ]

jobs:
  build-21:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.5.0

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew shadowJar

      - name: Upload JarFile
        uses: actions/upload-artifact@v4
        with:
          name: jar
          path: ./build/libs/VRCVideoLogViewer-1.0-SNAPSHOT-all.jar

  build-24:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.5.0

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew shadowJar

  release:
    needs: [build-21, build-24]
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Download JarFile
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/download-artifact@v4
        with:
          name: jar

      - name: Create Release Package
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          wget https://www.7-zip.org/a/7z2501-linux-x64.tar.xz
          tar -Jxvf ./7z2501-linux-x64.tar.xz
          mkdir ./tools
          mkdir ./tools/7z2501
          mv ./7zz ./tools/7z2501
          mv ./7zzs ./tools/7z2501
          mv ./History.txt ./tools/7z2501
          mv ./License.txt ./tools/7z2501
          mv ./MANUAL ./tools/7z2501
          mv ./readme.txt ./tools/7z2501
          chmod +x ./tools/7z2501/7zz
  
          wget https://r2.7mi.site/vrc/start_v0.6.x.bat
          wget https://r2.7mi.site/vrc/start_v0.6.x_forLinux.sh
          wget https://raw.githubusercontent.com/nicovrc-net/VRCVideoLogViewer/refs/heads/release/lang/ja.txt
          wget https://raw.githubusercontent.com/nicovrc-net/VRCVideoLogViewer/refs/heads/release/lang/en.txt
          wget https://raw.githubusercontent.com/nicovrc-net/VRCVideoLogViewer/refs/heads/release/lang/zh-Hans.txt
          wget https://raw.githubusercontent.com/nicovrc-net/VRCVideoLogViewer/refs/heads/release/lang/zh-Hant.txt
          wget https://raw.githubusercontent.com/nicovrc-net/VRCVideoLogViewer/refs/heads/release/lang/ko.txt
          
          mkdir ./tmp
          mv ./start_v0.6.x.bat ./tmp/start.bat
          mv ./start_v0.6.x_forLinux.sh ./tmp/start_forLinux.sh
          mkdir ./tmp/lang
          mv ./ja.txt ./tmp/lang
          mv ./en.txt ./tmp/lang
          mv ./zh-Hans.txt ./tmp/lang
          mv ./zh-Hant.txt ./tmp/lang
          mv ./ko.txt ./tmp/lang
          ./tools/7z2501/7zz a ./VRCVideoLogViewer.zip ./tmp/*
        shell: bash

      - name: Linux Bash Setup Test
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cd ./tmp
          chmod +x ./start_forLinux.sh
          screen -UAmdS test ./start_forLinux.sh
          sleep 15s
          if [ -d ./tools ]; then
            echo "Tools Folder OK"
            if [ -d ./tools/jdk-21.0.2 ]; then
              echo "OpenJDK OK"
              if [ -d ./tools/javafx-sdk-21.0.9 ]; then
                echo "JavaFX OK"
                if [ -d ./tools/ImageMagick ]; then
                  echo "ImageMagick OK"
                else
                  exit 1
                fi
              else
                exit 1
              fi
            fi
          else
            exit 1
          fi

        shell: bash

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: v${{ github.ref }}
          body: |
            - 正式版リリース
            - 多言語対応 (日本語/英語/中国語(简体/繁體)/韓国語)
            - ログフォルダが存在しない場合は選択ダイアログを出すようにした
          draft: false
          prerelease: false

      - name: Upload JarFile
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./VRCVideoLogViewer.zip
          asset_name: VRCVideoLogViewer.zip
          asset_content_type: application/java-archive

      - name: Delete File
        uses: geekyeggo/delete-artifact@v5
        with:
          name: |
            jar