# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master", "v1", "release" ]
    tags: ['*']
  pull_request:
    branches: [ "master", "v1", "release" ]

jobs:
  build-21:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Set up JDK 21
        uses: actions/setup-java@v5.2.0
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6.1.0

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew shadowJar

      - name: Create Package Files
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          tar -zcvf lang.tar.gz ./lang
          tar -zcvf run_batch.tar.gz ./run-batch
        shell: bash

      - name: Upload JarFile
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v7.0.0
        with:
          name: jar
          path: ./build/libs/VRCVideoLogViewer-1.0-SNAPSHOT-all.jar

      - name: Upload LangFile
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v7.0.0
        with:
          name: lang
          path: ./lang.tar.gz

      - name: Upload StartBatchFile
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v7.0.0
        with:
          name: run_batch
          path: ./run_batch.tar.gz

      - name: Upload ConfigFile
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v7.0.0
        with:
          name: config
          path: ./linux-package/config_for_package.txt

      - name: Upload PKGBUILD File
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v7.0.0
        with:
          name: PKGBUILD
          path: ./linux-package/PKGBUILD

  build-24:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Set up JDK 24
        uses: actions/setup-java@v5.2.0
        with:
          java-version: '24'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6.1.0

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew shadowJar

  download-7zip:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Download 7zip
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          wget https://github.com/ip7z/7zip/releases/download/26.00/7z2600-linux-x64.tar.xz
          mv 7z2600-linux-x64.tar.xz 7z.tar.xz
        shell: bash
      - name: Upload 7zip
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v7.0.0
        with:
          name: 7zip
          path: ./7z.tar.xz

  release:
    needs: [build-21, build-24, download-7zip]
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      packages: write
    steps:
      - name: Download 7zip
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/download-artifact@v8.0.1
        with:
          name: 7zip

      - name: Download JarFile
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/download-artifact@v8.0.1
        with:
          name: jar

      - name: Download LangFile
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/download-artifact@v8.0.1
        with:
          name: lang

      - name: Download RunBatch File
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/download-artifact@v8.0.1
        with:
          name: run_batch

      - name: Download PKGBUILD File
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/download-artifact@v8.0.1
        with:
          name: PKGBUILD

      - name: Create Release Package
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          tar -Jxvf ./7z.tar.xz
          mkdir ./tools
          mkdir ./tools/7z2600
          mv ./7zz ./tools/7z2600
          mv ./7zzs ./tools/7z2600
          mv ./History.txt ./tools/7z2600
          mv ./License.txt ./tools/7z2600
          mv ./MANUAL ./tools/7z2600
          mv ./readme.txt ./tools/7z2600
          chmod +x ./tools/7z2600/7zz
          
          tar -zxvf ./run_batch.tar.gz
          tar -zxvf ./lang.tar.gz
            
          mkdir ./tmp
          mv ./run-batch/start.bat ./tmp/start.bat
          mv ./run-batch/start_forLinux.sh ./tmp/start_forLinux.sh
          mv ./lang ./tmp
          mv ./VRCVideoLogViewer-1.0-SNAPSHOT-all.jar ./tmp
          ./tools/7z2600/7zz a ./VRCVideoLogViewer.zip ./tmp/*
        shell: bash

      - name: Linux Bash Setup Test
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cd ./tmp
          chmod +x ./start_forLinux.sh
          screen -UAmdS test ./start_forLinux.sh
          sleep 15s
          if [ -d ./tools ]; then
            echo "Tools Folder OK"
            if [ -d ./tools/jdk-21 ]; then
              echo "OpenJDK OK"
              if [ -d ./tools/javafx-sdk-21 ]; then
                echo "JavaFX OK"
              else
                exit 1
              fi
            fi
          else
            exit 1
          fi

        shell: bash

      - name: Download config File
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/download-artifact@v8.0.1
        with:
          name: config

      - name: Create deb Package
        if: startsWith(github.ref, 'refs/tags/')
        id: create_deb_package
        run: |
          INPUT_VERSION="$(echo "${{ github.ref }}" | sed -E "s,^refs/tags/,,")"
          
          mkdir -p ./deb-package
          mkdir -p ./deb-package/usr/share/VRCVideoLogViewer
          mkdir -p ./deb-package/usr/bin
          
          mkdir -p ./deb-package/DEBIAN
          
          echo -e "Package: VRCVideoLogViewer\nVersion: $INPUT_VERSION-1\nArchitecture: amd64\nMaintainer: Chino Nanami <tino_nanami@7mi.site>\nDescription: A tool for parsing VRChat logs to collect links to videos, images, and text content.\nDepends: openjdk-21-jdk, imagemagick, fonts-noto-cjk\nPre-Depends: curl, unzip" > ./deb-package/DEBIAN/control
          
          echo -e "#!/bin/bash\nif [ -x /usr/bin/VRCVideoLogViewer ]; then\nelse\n  rm /usr/share/VRCVideoLogViewer -fr" > ./deb-package/DEBIAN/postrm
          chmod +x ./deb-package/DEBIAN/postrm
          
          
          cp ./tmp/VRCVideoLogViewer-1.0-SNAPSHOT-all.jar ./deb-package/usr/share/VRCVideoLogViewer
          cp -r ./tmp/lang ./deb-package/usr/share/VRCVideoLogViewer
          mv ./config_for_package.txt ./deb-package/usr/share/VRCVideoLogViewer/config.yml
          sed -i 's/^## cd/cd/' ./tmp/start_forLinux.sh
          cp ./tmp/start_forLinux.sh ./deb-package/usr/bin/VRCVideoLogViewer
          chmod +x ./deb-package/usr/bin/VRCVideoLogViewer
          chmod 777 ./deb-package/usr/share/VRCVideoLogViewer/config.yml
          
          mkdir -p ./deb-package/usr/share/VRCVideoLogViewer/tools
          mkdir -p ./deb-package/usr/share/VRCVideoLogViewer/tools/7z2501
          
          mkdir -p ./deb-package/usr/share/VRCVideoLogViewer/tools/jdk-21/bin
          ln -s /usr/lib/jvm/java-21-openjdk-amd64/bin/java ./deb-package/usr/share/VRCVideoLogViewer/tools/jdk-21/bin/java
          
          echo -e "#!/bin/bash\ncurl https://download2.gluonhq.com/openjfx/21.0.10/openjfx-21.0.10_linux-x64_bin-sdk.zip --output /usr/share/VRCVideoLogViewer/tools/openjfx-21.0.10_linux-x64_bin-sdk.zip\nunzip /usr/share/VRCVideoLogViewer/tools/openjfx-21.0.10_linux-x64_bin-sdk.zip -d /usr/share/VRCVideoLogViewer/tools/" > ./deb-package/DEBIAN/postinst
          chmod +x ./deb-package/DEBIAN/postinst
          
          fakeroot dpkg-deb --build $WORK ./deb-package

        shell: bash

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: v${{ github.ref }}
          body: |
            - 起動バッチとアップデートバッチをPowershell化
          draft: false
          prerelease: false

      - name: Upload ZipFile
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./VRCVideoLogViewer.zip
          asset_name: VRCVideoLogViewer.zip
          asset_content_type: application/zip

      - name: Upload PKGBUILD File
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./PKGBUILD
          asset_name: PKGBUILD
          asset_content_type: text/plain

      - name: Upload deb package File
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./deb-package.deb
          asset_name: vrcvideologviewer.deb
          asset_content_type: application/vnd.debian.binary-package

      - name: Delete File
        if: startsWith(github.ref, 'refs/tags/')
        uses: geekyeggo/delete-artifact@v5
        with:
          name: |
            7zip
            jar
            run_batch
            PKGBUILD
            config